#!/usr/bin/env groovy

library(
    identifier: 'gitlab.hellotalk.com/test-issenn/Jenkinsfile_pipeline_library@develop',
    retriever: modernSCM(
        [
            $class: 'GitSCMSource',
            credentialsId: 'jenkins-generated-ssh-key',
            id: '1be36020-7d8e-40a0-99dc-113f2b036c28',
            remote: 'git@gitlab.hellotalk.com:test-issenn/Jenkinsfile_pipeline_library.git',
            traits: [
                [
                    $class: 'jenkins.plugins.git.traits.BranchDiscoveryTrait'
                ]
            ]
        ]
    )
)

env.CICD_TYPE = 'AndroidApp'
pipelineEntry()
